# To get started:
#
# pip install -r requirements.txt
# mkdocs serve
# Or just see the README
#
# ----------------------------------------------------------------------
site_name: APTrust Preservation Services
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
repo_url:  https://github.com/APTrust/preserv-docs
nav:
  - Home: index.md
  - Overview: overview.md
  - Code Structure: structure.md
  - Components:
      - components/index.md
      - components/redis.md
      - components/nsq.md
      - components/registry.md
      - components/s3.md
  - Workers:
      - workers/index.md
      - workers/anatomy.md
      - Ingest:
          - workers/ingest/index.md
          - workers/ingest/bucket-reader.md
          - workers/ingest/pre-fetch.md
          - workers/ingest/validator.md
          - workers/ingest/reingest-manager.md
          - workers/ingest/staging-uploader.md
          - workers/ingest/format-identifier.md
          - workers/ingest/preservation-uploader.md
          - workers/ingest/preservation-verifier.md
          - workers/ingest/recorder.md
          - workers/ingest/cleanup.md
      - Fixity: workers/fixity.md
      - Restoration: workers/restoration.md
      - Deletion: workers/deletion.md
  - Settings: settings.md
  - Docker: docker.md
  - Testing: testing.md
  - Auditor: auditor.md
